[project]
name = "redforecast"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.5.1",
    "loguru>=0.7.3",
    "notebook>=7.4.3",
    "pandas>=2.2.3",
    "python-decouple>=3.8",
]
